spring:
  liquibase:
    enabled: false
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}
  cloud:
    vault:
      generic:
        enabled: true
        profile-separator: '/'
        default-context: user-read-service
  application:
    name: user-read-service
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 0